import './screen/homeScreen.js'
import './component/homeScreen/homeHeader.js'
import './component/homeScreen/createPlusBtn.js'
import './component/homeScreen/quizInfoList.js'
import './component/homeScreen/quizInfoItem.js'

import './screen/quizCreator.js'
import './component/quizCreator/creatorHeader.js'
import './component/quizCreator/previewColumn.js'
import './component/quizCreator/previewItem.js'
import './component/quizCreator/addQuestionBtn.js'
import './component/quizCreator/quizInput.js'

import './screen/quizDisplay.js'
import './component/quizDisplay/quizHeader.js'
import './component/quizDisplay/quizContainer.js'

import './screen/quizRecords.js'
import './component/quizDisplay/recordContainer.js'
import './navigo.js'
import './screen/quizStarter.js'
import './screen/login.js'
import './screen/signUp.js'
import './component/inputWrapper.js'
import './component/quizDisplay/starterContainer.js'
import "./test.js"